"use client"
import Head from "next/head";
import "~/styles/globals.css";
import { Inter } from "next/font/google";
import { NextUIProvider } from "@nextui-org/react";
import {  useEffect, useState } from "react";
import Loader from "../components/ui/elements/Loader/Loader";



const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
})

 {
  const [loading, setLoading] = useState(true);
  const [contentLoaded, setContentLoaded] = useState(false);

  useEffect(() => {
    setTimeout(() => {
      setLoading(false);
    }, 1000);

    setTimeout(() => {
      setContentLoaded(true);
    }, 50);
  }, []);
  useEffect(() => {
    document.title = 'Pan Pacific Hotel';
  }, []);
  return (
    <>
   <Head>
        <meta
          name="description"
          content="Generated by create-t3-app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    <html lang="en">
      <body className={`font-sans ${inter.variable}`}>
      
        <NextUIProvider>
      
          <main>
        {loading ? (
          <>
            <Loader />
          </>
        ) : (
          (
            <div style={{ visibility: contentLoaded ? "visible" : "hidden" }}>
               {children}
            </div>
          )
        )}
           </main>
        </NextUIProvider>
       
      </body>
    </html>
    </>
  );
}
